### ISSUE TITLE
Add alias functionality

### ISSUE THREAD

**Issue by hrmay** [Grumblesaur/atropos#52]
Add some type of alias functionality (possibly with an alias type). An example of how this could work:

```diff
+roll core test = "abc"
"abc"
+roll my test => core test
core test
+roll my test
"abc"
+roll core test = "xyz"
"xyz"
+roll my test
"xyz"
```

**Comment by Grumblesaur** [comment]
Used a different semantic approach for "aliases", which are now a sort of custom literal or macro for executing a user-defined function. Syntax:

```identifier "aliases" expression``` where `expression` must be a function literal or identifier which evaluates to a function. This function must take no arguments. This function is stored in the alias named `identifier`, and the function is automatically evaluated when the identifier is invoked in an expression, except when that expression is

```"inspect" identifier```

which can be used to retrieve the function from the alias named `identifier`.
