### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by daneckel** [Grumblesaur/atropos#69]
The Atropos bot has been down on discord for a few weeks. Is this permanent? Our party loves using this straight forward dice rolling bot.

**Comment by Grumblesaur** [comment]
Certain dependencies have updated and broken the bot; a fix is forthcoming,
but it might take a while.

**Comment by Grumblesaur** [comment]
A fix has been implemented; henceforth Atropos should only go down for maintenance or power outages.
